### ISSUE TITLE
UI “Freaks Out” on Android

### ISSUE THREAD

**Issue by opportunex** [SniperGER/Framework7-WatchUI#2] opened 2015-05-12 19:32 UTC
Great job on WatchUI! It's a great addition to Framework7!! 

Hey, a quick question: I know that the Watch UI was built for the apple watch and that your main focus is obviously iOS. But I have a really neat adaptation of the WatchUI interface and I'm using it as a dashboard for my app. 

It works great on iOS (perfect actually - thanks!), but on Android the app icons fly all over the screen and the touch tracking is way off. I'm pretty adept at jQuery and I can understand your code very well, but I was wondering if you had any ideas where I could start looking to fix the issue for android. Thanks :)

**Comment by SniperGER** [comment] 2015-05-12 19:35
The problem is that I do not own any Android devices, nor have I setup any simulators. Therefore I haven't had a chance to test the behaviour on Android yet.

I might actually look into this sometime when I have the chance.

**Comment by opportunex** [comment] 2015-05-12 20:03
Thanks for the quick response.  I think the best way to handle it right now would be to disable the animations on android (drag around part) and get to the “nitty gritty” later.  Any suggestion on how to quickly disable the touch dragging?  In any event, I’ll let you know what I come up with J

**Comment by SniperGER** [comment] 2015-05-12 20:27
A quick fix (until I implement an "official" way) would be to remove the event handlers in line 134.

Normally it should say
```
core.params.screenContainer.on("touchstart mousedown", function(e) {
```

Just remove the "touchstart mousedown" part but leave an empty string (""). This way the core doesn't have any events to listen to and can't trigger the animation while dragging.

If the issue persists when moving to an app, please tell me. If that's the case I need to disable transitions to app screens.

**Comment by opportunex** [comment] 2015-05-12 20:35
Thanks again for the quick reply!  I’ll try that and let you know.  Like I said, it works great on iOS and other than the touch/drag thing, all other interactions perform well on android too.

**Closed** 2016-06-11 09:28 UTC
